# Generated by Django 2.2.1 on 2020-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(max_length=64, verbose_name='组织机构id')),
                ('flow_type', models.CharField(blank=True, default=1, max_length=1, verbose_name='流水类型')),
                ('purchase_content', models.CharField(blank=True, max_length=32, null=True, verbose_name='变动原因')),
                ('operator', models.CharField(max_length=64, verbose_name='操作人')),
                ('init_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='起始金额')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变动金额')),
                ('now_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最后金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
