# Generated by Django 2.2.1 on 2020-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='init_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='起始金额'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='now_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最后金额'),
        ),
    ]
